export const GET_GAMES = "GET_GAMES";
export const GET_GAMES_DETAIL = "GET_GAMES_DETAIL";
export const GET_GAMES_NAME = "GET_GAMES_NAME";
export const FILTER_GAMES = "FILTER_GAMES";
export const FILTER_GAMES_CREATE = "FILTER_GAMES_CREATE";
